---
ansible_user: admin
ansible_ssh_private_key_file: ~/.ssh/id_rsa
ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_become_method: sudo

required_linux_repos:
- epel-release
- elrepo-release

required_linux_packages:
- ipset
- ipvsadm
- iptables
- libcgroup-tools
- iproute-tc
- python3
- htop
