all:
  children:
    kube_cluster:
      children:
        kube_masters:
          children:
            kube_primary_master:
              hosts:
                kube-master1:
            kube_secondary_masters:
              hosts:
                kube-master2:

        kube_workers:
          hosts:
            kube-worker1:
            kube-worker2:

    kube_proxy:
      hosts:
        kube-proxy:

    docker_hosts:
      hosts:
        kube-proxy:
