---
- name: Install system dependencies
  hosts: all
  become: yes

  tasks:
  - name: Install required system package repos
    dnf:
      name: '{{ required_system_repos }}'
      state: present

  - name: Install required system packages
    dnf:
      name: '{{ required_system_packages }}'
      state: present
