---
- name: Install Envoy
  hosts: kube_proxy
  become: yes

  tasks:
  - name: Create Envoy config directory
    file:
      path: '{{ envoy_config_path }}'
      state: directory

  - name: Copy Envoy proxy configuration
    copy:
      src: files/proxy/envoy-config.yaml
      dest: '{{ envoy_config_file }}'
      mode: 0644
    notify: restart_envoy

  - name: Launch Envoy container
    docker_container:
      name: '{{ envoy_container_name }}'
      image: '{{ envoy_container_image }}'
      command: '-c {{ envoy_config_file }}'
      volumes:
      - '{{ envoy_config_path }}:{{ envoy_config_path }}:ro'
      published_ports:
      - '{{ envoy_admin_port }}:{{ envoy_admin_port }}'
      - '{{ envoy_kube_control_plane_port }}:{{ envoy_kube_control_plane_port }}'
      restart_policy: always
      container_default_behavior: no_defaults
      state: started

  handlers:
  - name: Restart Envoy
    docker_container:
      name: '{{ envoy_container_name }}'
      restart: true
      state: started
    listen: restart_envoy
