---
- name: Install system dependencies
  hosts: all
  become: yes

  tasks:
    - name: Install additional repos
      dnf:
        name: '{{ linux_extra_repos }}'
        state: present

    - name: Install additional system packages
      dnf:
        name: '{{ linux_extra_packages }}'
        state: present

    - name: Install required Python modules
      pip:
        name: '{{ python_modules }}'
        state: present
