---
- name: Setup Kubernetes on primary master node
  hosts: kube_masters_primary
  become: yes

  tasks:
    - name: Check if Kubernentes is already installed
      stat:
        path: '{{ kube_config_kublet }}'
      register: kube_installation

    - name: Initialise Kubernetes cluster
      block:
        - name: Pull Kubernetes control plane container images
          command: >
            kubeadm config images pull
          changed_when: false

        - name: Create Kubernetes certs directory
          file:
            path: '{{ kube_config_pki_directory }}'
            mode: 0755
            state: directory

        - name: Copy root CA key
          copy:
            src: files/kubernetes/masters/ca.key
            dest: '{{ kube_config_pki_directory }}'
            mode: 0600

        - name: Copy root CA cert
          copy:
            src: files/kubernetes/masters/ca.crt
            dest: '{{ kube_config_pki_directory }}'
            mode: 0644

        - name: Copy Kubernentes init config
          template:
            src: templates/kubernetes/kubeadm-init-config.yml.j2
            dest: ~/kubeadm-init-config.yml
            mode: 0644

        - name: Bootstrap Kubernetes cluster
          command: >
            kubeadm init --config ~/kubeadm-init-config.yml 

        - name: Install Calico pod networking
          command: >
            kubectl apply --filename {{ kube_pod_network_config_uri }}
          environment:
            KUBECONFIG: '{{ kube_config_admin }}'
          changed_when: false

        - name: Install Nginx ingress controller
          command: >
            kubectl apply --filename {{ kube_ingress_controller_config_uri }}
          environment:
            KUBECONFIG: '{{ kube_config_admin }}'
          changed_when: false
      when: not kube_installation.stat.exists

    - name: Upload certs for initialising secondary masters
      command: >
        kubeadm init phase upload-certs
          --certificate-key {{ kube_join_upload_certs_key }}
          --skip-certificate-key-print
          --upload-certs
      changed_when: false

- name: Join secondary master nodes
  hosts: kube_masters_secondary
  become: yes

  tasks:
    - name: Check if Kubernentes is already installed
      stat:
        path: '{{ kube_config_kublet }}'
      register: kube_installation

    - name: Join Kubenetes cluster
      block:
        - name: Copy Kubernentes master join config
          template:
            src: templates/kubernetes/kubeadm-join-master-config.yml.j2
            dest: ~/kubeadm-join-master-config.yml
            mode: 0644

        - name: Join Kubernetes cluster as master
          command: >
            kubeadm join --config ~/kubeadm-join-master-config.yml
          changed_when: false
      when: not kube_installation.stat.exists

- name: Setup kubenetes config in user profiles
  hosts: kube_masters
  become: yes

  tasks:
    - name: Update root user profile with KUBECONFIG
      lineinfile:
        path: ~/.bash_profile
        line: 'export KUBECONFIG={{ kube_config_admin }}'
        state: present

    - name: Create $HOME/.kube directory within Ansible user's profile
      file:
        path: '$HOME/.kube'
        state: directory
      become: no
      register: kube_directory

    - name: Copy Kubernetes config to $HOME/.kube of Ansible user
      copy:
        src: '{{ kube_config_admin }}'
        dest: '{{ kube_directory.path }}/config'
        owner: '{{ kube_directory.uid }}'
        group: '{{ kube_directory.gid }}'
        remote_src: yes
