---
- name: Update system dependencies
  hosts: all
  become: yes

  tasks:
    - name: Update system packages skipping excluded ones
      dnf:
        name: '*'
        exclude:
          - docker*
          - kube*
        update_only: yes
        state: latest
