admin:
  access_log_path: /dev/null
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901

static_resources:
  listeners:
  - name: tcp_6443
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 6443
    filter_chains:
    - filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          cluster: kube_cplane
          stat_prefix: kube_cplane

  clusters:
  - name: kube_cplane
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    dns_lookup_family: V4_ONLY
    connect_timeout: 0.40s
    load_assignment:
      cluster_name: kube_cplane
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: kube-master1
                port_value: 6443
        - endpoint:
            address:
              socket_address:
                address: kube-master2
                port_value: 6443
    health_checks:
    - tcp_health_check: {}
      timeout: 1s
      interval: 5s
      healthy_threshold: 1
      unhealthy_threshold: 1
